MyEBooks/Controllers/NewReleaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProductsEStore.Models;

namespace ProductsEStore.Controllers
{
    public class NewReleaseController : MyBaseController
    {
        public ActionResult Index()
        {
            // Dependency Injection
            var newRelease = new NewRelease(_repository);
            newRelease.NavigationBar.RenderSortByListMenu = false;
            return View("Index", newRelease);
        }

    }
}

MyEBooks/Views/Shared/Result.cshtml
@model MyEBooks.Models.ProductListViewResult
@{
    ViewBag.Title = "Search Results";
    int cols = 4;
    int totalBookCount = Model.ProductCount;
    int rows = (totalBookCount / cols) + (totalBookCount % cols > 0 ? 1 : 0);
    int bookIndex = 0;
}
@if (@Model.FoundResult)
{
    <div class="visible-lg-inline visible-md-inline">
        <h2>
            @Model.Header.Message
        </h2>
    </div>
    <div class="visible-sm-inline visible-xs-inline">
        <h3>
            @Model.Header.Message
        </h3>
    </div>
    
    
@*<div>
        <span>PageSize: @Model.Pager.PageSize</span> <span>PagerDisplayLength: @Model.Pager.PagerDisplayLength</span>
        <span>TotalItems: @Model.Pager.TotalItems</span> <span>TotalPages: @Model.Pager.TotalPages</span>
    </div>*@
    <div class="container-fluid">
        @for (int row = 1; row <= rows && bookIndex < totalBookCount; row++)
        {
            <div class="row">
                @for (int col = 1; col <= cols && bookIndex < totalBookCount; col++)
                {
                    var lg = (12 / cols);
                    var md = ((12 / cols) * 2) > 12 ? 12 : ((12 / cols) * 2);
                    var sm = 12;
                    var xs = sm;
                    
                    string colLayout = string.Format("col-lg-{0} col-md-{1} col-sm-{2} col-xs-{3}", lg, md, sm, xs);
                    <div class="@colLayout">
                        <div class="panel panel-info">
                            <div class="panel-heading text-nowrap">
                                <h5 class="panel-title" style="overflow: hidden">@Model.ViewProducts[bookIndex].Title</h5>
                            </div>
                            <div class="panel-body">
                                <img src="http://ecx.images-amazon.com/images/I/514%2BoWhnajL._SL200_.jpg" alt="phyton guide"
                                    class="img-thumbnail img-responsive">
                            </div>
                        </div>
                    </div>
                    bookIndex++;
                }
            </div>
        }
        @*@foreach (var book in @Model.DisplayedBooks)
        {
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-info">
                        <div class="panel-heading text-nowrap">
                            <p class="panel-title" style="overflow: hidden">@book.Title</p>
                        </div>
                        <div class="panel-body">
                            <img src="http://ecx.images-amazon.com/images/I/514%2BoWhnajL._SL200_.jpg" alt="phyton guide"
                                class="img-thumbnail img-responsive">
                        </div>
                    </div>
                </div>
            </div>
        }*@
        <div class="container-fluid text-center">
            @Html.Partial("_PagerPartial", @Model.Pager)
        </div>
    </div>
}
else
{
    <h1 class="h2 alert-danger">
         @Model.Header.Message
    </h1>
    <p>
        Sorry, no ebooks matched your criteria.</p>
}

MyEBooks/Views/Shared/VamsiLayout.cshtml
@model MyEBooks.Models.ViewModelBase

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>VamsiLayout</title>
</head>
<body>
@Model.RenderSoryBy
    <div>
        @RenderBody()
    </div>
</body>
</html>

MyEBooks/Views/Shared/_AdsPartial.cshtml
<div class="well">
    <p>
        ADS</p>
</div>
<div class="well">
    <p>
        ADS</p>
</div>

MyEBooks/Views/Shared/_BreakingNewsPartial.cshtml
<div class="ticker-container">
    <div class="ticker-caption">
        <p>Breaking News</p>
    </div>
    <ul>
        <div>
            <li><span>Breaking News 1 &ndash; <a href="#">read more</a></span></li>
        </div>
        <div>
            <li><span>Breaking News 2 &ndash; <a href="#">read more</a></span></li>
        </div>
        <div>
            <li><span>Breaking News 3 &ndash; <a href="#">read more</a></span></li>
        </div>
        <div>
            <li><span>Breaking News 4 &ndash; <a href="#">read more</a></span></li>
        </div>
        <div>
            <li><span>Breaking News 5 &ndash; <a href="#">read more</a></span></li>
        </div>
    </ul>
</div>

MyEBooks/Views/Shared/_FooterPartial.cshtml
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <ul class="list-inline">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Privacy Policy", "PrivacyPolicy", "Home")</li>
                <li>@Html.ActionLink("FAQ", "FAQ", "Home")</li>
                <li>@Html.ActionLink("RSS", "RSS", "Home")</li>
                <li>@Html.ActionLink("DMCA", "DMCA", "Home")</li>
                <li>@Html.ActionLink("Donate", "Donate", "Home")</li>
                <li>@Html.ActionLink("Sitemap", "Sitemap", "Home")</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            Copyright © 2016 @Html.ActionLink("MyEbook", "Index", "Home")
        </div>
    </div>
</div>

MyEBooks/Views/Shared/_HomeLayout.cshtml
@model MyEBooks.Models.ViewModelBase
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/styles")
    @Scripts.Render("~/bundles/scripts")
    @*@Html.Partial("_HtmlHeadPartial")*@
</head>
<body>
    <header>
        @Html.Partial("_NavbarPartial",@Model.NavigationBar)
    </header>
    <div class="container-fluid text-center">
        <div class="row content">
            <div class="col-sm-1 sidenav">
            </div>
            <div class="col-sm-8 text-left">
                <p>@RenderBody()</p>
            </div>
            <div class="col-sm-3 sidenav">
                @*<div class="row content">
                    <div class="col-lg-12">
                        @Html.Partial("_TagCloudRandomPartial")
                    </div>
                </div>*@ @*<div class="row content">
                    <div class="col-lg-12">
                        @Html.Partial("_TagCloudSquarePartial")
                    </div>
                </div>*@
            </div>
        </div>
    </div>
    <footer class="container-fluid text-center">
        @Html.Partial("_FooterPartial")
    </footer>
</body>
</html>

MyEBooks/Views/Shared/_HtmlHeadPartial.cshtml
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="~/Content/SiteCss/site.css">
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- START : RecentActivityTicker Related Stuff --->
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css">
<link href="http://www.jqueryscript.net/css/jquerysctipttop.css" rel="stylesheet"
    type="text/css">
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<link href="~/Content/RecentActivityTickerCss/Ra-ticker.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/RecentActivityTickerJs/Ra-ticker.js" type="text/javascript"></script>
@*<script type="text/javascript">
    $(function () {
        $(".demo").bootstrapNews({
            newsPerPage: 3,
            autoplay: true,
            pauseOnHover: true,
            direction: 'up',
            newsTickerInterval: 4000,
            onToDo: function () {
                //console.log(this);
            }
        });
    });
</script>*@
<!-- END : RecentActivityTicker Related Stuff --->
<!-- START : BreakingNews Ticker Related Stuff --->
<link href="~/Content/BreakingNewsTickerCss/Bn-ticker.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/BreakingNewsTickerJs/Bn-ticker.js"></script>
<!-- END : BreakingNews Ticker Related Stuff --->
<!-- START : TagCloudSquare Related Stuff --->
<link href='~/Content/TagCloudSquareCss/jquerysctipttop.css' rel='stylesheet' type='text/css'>
<link href="~/Content/TagCloudSquareCss/Roboto.css" rel="stylesheet" type="text/css">
<script src="~/Scripts/TagCloudSquareJs/jquery.tagcloud.js"></script>
<script src="~/Scripts/TagCloudSquareJs/jquery-1.11.3.min.js"></script>
<!-- END : TagCloudSquare Related Stuff --->

MyEBooks/Views/Shared/_Layout.cshtml
@model MyEBooks.Models.ViewModelBase
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/bundles/styles")
    @Scripts.Render("~/bundles/scripts")
    @*@Html.Partial("_HtmlHeadPartial")*@
</head>
<body>
    <header>
        @Html.Partial("_NavbarPartial", @Model.NavigationBar)
    </header>
    <div class="container-fluid text-center">
        @* <div class="row">
            <div class="col-lg-12">
                @Html.Partial("_BreakingNewspartial");
            </div>
        </div>*@
        <div class="row content">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-8 text-left">
                <p>@RenderBody()</p>
            </div>
            <div class="col-sm-3 sidenav">
                @Html.Partial("_PopularTagsPartial", new MyEBooks.Models.SiteMapData().PopularTagData)
                @Html.Partial("_AdsPartial")
            </div>
        </div>
    </div>
    <footer class="container-fluid text-center">
        @Html.Partial("_FooterPartial")
    </footer>
</body>
</html>

MyEBooks/Views/Shared/_NavbarPartial.cshtml
@model MyEBooks.Models.NavigationBar
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid ">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">MyEbook</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                    aria-haspopup="true" aria-expanded="false">Books <span class="caret"></span></a>
                    <ul class="dropdown-menu scrollable-menu" style="height: auto">
                        @foreach (var categoryListItem in Model.Categories)
                        {
                            <li>@Html.ActionLink(categoryListItem.Text, categoryListItem.BackEndPurposeText, "category")</li>
                        }
                    </ul>
                </li>
                <li>@Html.ActionLink("Top Sellers", "Index", "TopSellers")</li>
                <li>@Html.ActionLink("Most Reviews", "Index", "MostReviews")</li>
                <li>@Html.ActionLink("New Release", "Index", "NewRelease")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @if (Model.RenderSortByListMenu)
                {
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                        aria-haspopup="true" aria-expanded="false">Sort By <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @foreach (var sortByListItem in Model.SortByListItems)
                            {
                                <li>@Html.ActionLink(sortByListItem.Text, "Index", new { sort = @sortByListItem.SeoFriendlyText })</li>
                            }
                           @* <li>@Html.ActionLink("PostDate(Default)", "Index", new { sort = "post-date" })</li>
                            <li>@Html.ActionLink("Upload Date", "Index", new { sort = "upload" })</li>
                            <li>@Html.ActionLink("Publication Date", "Index", new { sort = "daterank" })</li>
                            <li>@Html.ActionLink("Most Reviews", "Index", new { sort = "review-count-rank" })</li>
                            <li>@Html.ActionLink("Avg. customer Review", "Index", new { sort = "average-review-rank" })</li>
                            <li>@Html.ActionLink("Most Downloads", "Index", new { sort = "download-count-rank" })</li>*@
                        </ul>
                    </li>
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <form class="navbar-form navbar-left form-inline" method="post" action="/search/index">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for..." id="keyword"
                            name="keyword">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                Go!</button>
                        </span>
                    </div>
                    </form>
                </li>
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

MyEBooks/Views/Shared/_NewsTickerPartial.cshtml
@*<div id="jquery-script-menu">
    <div class="jquery-script-center">
        <div class="jquery-script-clear">
        </div>
    </div>
</div>*@
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-list-alt"></span><b>News</b></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <ul class="demo1">
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/1.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/2.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/3.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/4.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/5.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/6.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                                <li class="news-item">
                                    <table cellpadding="4">
                                        <tr>
                                            <td>
                                                <img src="~/NewsTickerImages/7.png" width="60" class="img-responsive img-circle" />
                                            </td>
                                            <td>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in venenatis enim...
                                                <a href="#">Read more...</a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
</div>

MyEBooks/Views/Shared/_PagerPartial.cshtml
@model MyEBooks.Models.Pager
@{
    int i = 0;
    string className = "";
}
@if (@Model.IsRenderable)
{
    <nav aria-label="Page navigation">
        <ul class="pagination pagination-sm">
            @if (@Model.IsFirstEnabled)
            {
                <li><a href="@Url.Action("index", new { pageNo = 1 })" ><span aria-hidden="true">&laquo;&laquo;</span>
                </a></li>
            }
            else
            {
                <li class="disabled"><a href="@Url.Action("index", new { pageNo = 1 })" ><span aria-hidden="true">
                    &laquo;&laquo;</span> </a></li>
            }
            @if (@Model.IsPreviousEnabled)
            {
                <li><a href="@Url.Action("index", new { pageNo = @Model.CurrentIndex - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span> </a></li>
            }
            else
            {
                <li class="disabled"><a href="" aria-label="Previous"><span aria-hidden="true">&laquo;</span>
                </a></li>
            }
            @for (i = @Model.StartIndex; i <= @Model.EndIndex; i++)
            {
                className = "";
                if (i == @Model.CurrentIndex)
                {
                    className = "active";
                }
                <li class="@className">@Html.ActionLink(@i.ToString(), "index", new { pageNo = @i })</li>
            }
            @if (@Model.IsNextEnabled)
            {
                <li><a href="@Url.Action("index", new { pageNo = @Model.CurrentIndex + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span> </a></li>
            }
            else
            {
                <li class="disabled"><a href="" aria-label="Next"><span aria-hidden="true">&raquo;</span>
                </a></li>
            }
            @if (@Model.IsLastEnabled)
            {
                <li><a href="@Url.Action("index", new { pageNo = @Model.TotalPages })"><span aria-hidden="true">
                    &raquo;&raquo;</span> </a></li>
            }
            else
            {
                <li class="disabled"><a href="@Url.Action("index", new { pageNo = @Model.TotalPages })">
                    <span aria-hidden="true">&raquo;&raquo;</span> </a></li>
            }
        </ul>
    </nav>
}

MyEBooks/Views/Shared/_PopularTagsPartial.cshtml
@{
    ViewBag.PanelTitle = "Popular Tags:";
}
@model MyEBooks.Models.PopularTagData
@Styles.Render("~/bundles/tagCloudstyles")
@Scripts.Render("~/bundles/tagCloudscripts")
<script type="text/javascript">

    if (!String.format) {
        String.format = function (format) {
            var args = Array.prototype.slice.call(arguments, 1);
            return format.replace(/{(\d+)}/g, function (match, number) {
                return typeof args[number] != 'undefined' ? args[number] : match;
            });
        };
    }

    function LoadPopularTags(filterBy, totalItemsToGet) {
        var apiPath = String.format("/api/PopularTags/{0}/{1}", filterBy, totalItemsToGet);
        $.getJSON(apiPath, function (data) {
            $("#popularTagCloud").empty();

            $.each(data, function (index, element) {
                var url = String.format("<a href='/search/{0}' rel='{1}'>{0} </a>", element.Keyword, element.Count);
                $("#popularTagCloud").append(url);
            });

            $("#popularTagCloud a").tagcloud({
                size: { start: 12, end: 36, unit: "px" },
                color: { start: '#3498DB', end: '#46CFB0' }
            });
        });
    }

    $(function () {
        $("#popularTagCloud a").tagcloud({
            size: { start: 12, end: 36, unit: "px" },
            color: { start: '#3498DB', end: '#46CFB0' }
        });

        $("#filterBtnPopularTagRecentActivity,#filterBtnPopularTagRecentCount").on("click", function () {
            LoadPopularTags($(this).attr('data-api'), $(this).attr('data-items'));
        });
    });
</script>
<div class="panel panel-success">
    <div class="panel-heading text-nowrap">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="btn-group">
                        <button type="button" class="btn btn-info">
                            Popular Tags</button>
                        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-filter"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li id="filterBtnPopularTagRecentActivity" data-api="recent" data-items="@Model.TotalTagsToGet">
                                <a href="#">Recent</a></li>
                            <li id="filterBtnPopularTagRecentCount" data-api="hit" data-items="@Model.TotalTagsToGet">
                                <a href="#">Hit Count</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div id="popularTagCloud">
            @foreach (var tag in Model.PopularTags)
            {
                @Html.ActionLink(@tag.TagName + " ", "index", "search", new { keyword = @tag.TagName }, new { rel = @tag.Weight });
            }
        </div>
    </div>
</div>

MyEBooks/Views/Shared/_TagCloudPartial.cshtml
<script type="text/javascript">
    $(function () {
        $.getJSON("/api/TagCloud", function (data) {
            var items = [];
            $.each(data, function (index, element) {
                items.push({ text: element.Text, weight: element.Weight, link: element.Link });
            });
            $("#tagCloud").jQCloud(items)
        });
    });
</script>
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <div id="tagCloud" style="width: 350px; height: 250px;">
            </div>
        </div>
    </div>
</div>